### PR TITLE
Add locale for brazilian portuguese

### PR DESCRIPTION
**Pull request by HenriqueDerosa**
## More details
I added a few items to a new file called `pt-BR` where I put some of the main texts to say `it works in Portuguese`. 

The only thing left is the sanctoral, it's not complete yet, but it's a good start to have it in Portuguese.

If I need to make any changes, just tell me. I really loved these repositories of `romcal`.  Thanks

### CODE REVIEW

**Comment by tukusejssirs** [comment]
@HenriqueDerosa, thank you for your contribution! However, we are in the middle or refactoring of the code (we move it entirely into TypeScript), therefore it would be awesome if you could create a PR against `_F-TypeScript` branch? :smiley:

**Comment by emagnier** [comment]
🎉 Awesome! Thanks @HenriqueDerosa for your contribution!

We could merge it here. There is no breaking changes, it's only about locales on limited files, and that one is easy to back port on our working branches.

The `_F-TypeScript` is even not ready yet for development usage (with no ETA for the time being).

**Review by emagnier — APPROVED** [review]

**Comment by tukusejssirs** [comment]
@emagnier, I thought we want to work on the TS branch primarily, that’s why I suggested to rebase the changes.

**Comment by emagnier** [comment]
Yes, in fact it depends on the type of contributions. 
And also because I don't see the work from the TS branch out soon (there is still a lot of work to do, with a required testing phase for all kinds of usages). 

The rewrite of the codebase is currently a special situation, so for the time being, we might have to discern on a case-by-case basis. Here it's a simple contribution (with a great value!), that don't have too much impact on our codebase 😄

**Comment by emagnier** [comment]
(ping FYI @pejulian)

**Comment by pejulian** [comment]
Happy Easter everyone!

I've been away for awhile due to other commitments.

However, I hope to be able to resume work with the TS branch soon. I think we should consider cutting a working version of the TS branch and have that published for general use before proceeding with the other changes discussed. That way, the new implementation won't be stuck in development phase forever. 

The new version we cut should address any critical bugs in the new code base but otherwise retain most of the functionality as before.

What do you guys think about that?

**Comment by emagnier** [comment]
Hey @pejulian, thanks for your message! Maybe we could continue to discuss about that here https://github.com/romcal/romcal/issues/181#issuecomment-621197401, so it's easier to keep the track?

**Pull request merged**
