### PR TITLE
Change `wladyslaw_of_gielniow_priest` to `ladislas_of_gielniow_priest`

### PR DESCRIPTION
**Pull request by tukusejssirs**

### CODE REVIEW

**Comment by emagnier** [comment]
Is it ready to be merge?

**Comment by tukusejssirs** [comment]
> Is it ready to be merge?

Yes, though I’ve just fixed an issue, but it is ready to merge. :smiley:

**Comment by emagnier** [comment]
You often put 👍 everywhere and I'm not always sure about the meaning.
Does it mean here that you just read it, or you approve and we can merge it?

**Comment by emagnier** [comment]
Ok let's do it. Thanks for this PR!

**Comment by emagnier** [comment]
Oops I copy pasted my comment in the description of this commit, I'll have to change that.

**Comment by emagnier** [comment]
Last commit amended. Situation fixed. 😸

**Comment by tukusejssirs** [comment]
> You often put +1 everywhere and I'm not always sure about the meaning.
> Does it mean here that you just read it, or you approve and we can merge it?

You’re right, it is ambiguous.

Mostly, I use them to say I’ve read the particular comment and have nothing to say. Sometimes it also means I agree with the comment. Sorry about that.

Do you have any requirement of the emojis? :smiley:

**Comment by emagnier** [comment]
I don't know what's the best. Maybe avoid them when it's possibly ambiguous.

**Comment by tukusejssirs** [comment]
Okay, I’ll do that. :smiley:

**Pull request merged**
