### PR TITLE
Corrected typos in localization and add Polish strings

### PR DESCRIPTION
**Pull request by jarosz**
Hi!

I have corrected some typos in localization.json, especially those coming from transliterating Polish character 'ł' as 't' instead of 'l'.

I have also localized Polish strings according to Missale Romanum for Polish dioceses.

### CODE REVIEW

**Comment by pejulian** [comment]
Hi jarosz,

Thank you for contributing to romcal!
Do allow me some time to review the changes and if all is good, I will merge them.

**Comment by jarosz** [comment]
Hi!

Since my first contribution I've made some other changes that involved
adjustment not only in translation, but in design as well, so github now
states, that "The Travis CI build failed".

I needed to generate my calendar quickly, so I've commited my code, but it
still requires some design decisions and correcting tests. Since the
mergeAndSort function won't overwrtite duplicates, then you have to remove
them by hand when there is a celebration which has different date in
national calendar. For example the memorial of John of Kety is celebrated
Dec 23 worldwide, but Oct 20 in Poland, which ends up with a duplicate. I
don't know if this is by design, but I had no time for asking questions.

This was my first pull request ever, and since I've always used git as a
replacement for svn I think I made it wrong. Github included in the request
also those changes I've commited later. Now I think I should create a
single branch for each feature and make separate pull request for those
branches, so you can easier choose what to merge in your repository.

Regards

Jacek Roszkowski

2015-03-20 11:22 GMT+01:00 pejulian <notifications@github.com>:

**Comment by jarosz** [comment]
Hi

I've made some other design changes, which you may consider implementing
better, for example:
* some global switches to determine the date of Ascension (in Poland it's
on Sunday, not Thursday), Epiphany (always Jun 6), coprus Christi (on
Thursday) - my version is a quick hack.
* what if celebrations which are joined in general calendar, are separated
in national (e.g. saintHedwigOrSaintMargaretMaryAlacoque in Poland have
different dates) - I've used common localization string and split it in
two, but maybe separate localizations should be created to avoid confusion
(but harder to maintain in translation)

Jacek Roszkowski

2015-03-21 10:25 GMT+01:00 Jacek Roszkowski <j.roszk@gmail.com>:

**Comment by pejulian** [comment]
Hi jarosz,

Thank you for your contributions to romcal.
I have re-written the entire module from scratch for better extensibility and functionality.
Some of the fixes you highlighted are fixed by the rewrite.

[1] New switches to handle the following (see README.md):
- Baptism calculation
- Ascension on 7th Sunday of Easter
- Corpus Christi on Thursday
have been added.

[2] Colors can now be overwritten
[3] Re-written code for managing duplicates (_getCalendar and _applyDates in calendar.js)
  
Currently, I am working on developing a more manageable localization framework for celebration names for 

romcal. I will be sure to add in the localized Polish terms that you have provided when the framework is 

ready.

I however, do need some clarifications for:

saintAngelaMericiVirgin 
- supposed to be set to Jan 29 but that date is already occupied by blessedBoleslawaMariaLamentVirgin

saintAdalbertBishopAndMartyr
- If this solemnity lands anywhere in Holy Week up to Divine Mercy Sunday, it will be transferred to the Monday after Divine Mercy Sunday. However, the same rule applies to the feast of the Annunciation. If both Annunciation and saintAdalbert lands on the same day, then saintAdalbert is moved to the day after Annunciation (Tuesday). Is this reasoning acceptable?

**Comment by jarosz** [comment]
Hi!

Thank you for your response. These are clarifications you have asked for:

1. saintAngelaMericiVirgin. According to official liturgical calendar for
polish dioceses
http://www.kkbids.episkopat.pl/uploaded/KalendarzDiecezjiPolskich-2013-02-28_2.pdf
saint Angela Merici and blessed Bolesława Maria Lament may be celebrated in
Poland on Jan 29 as optional memorial, the date is different than in
general calendar probably because on Jan 27 we celebrate memorial of
blessed Jerzy Matulewicz, bishop.
2. saintAdalbertBishopAndMartyr. It's impossible for Annunciation and
saintAdalbert to land on the same day, because both have fixed dates with
more than two week distance: the former is Mar 25, the latter is Apr 23.
The same rule applies to both in relation to the Holy Week and Easter
Octave, because of variable Easter Sunday date (Mar 22 - Apr 25), but
regardless of Easter date, only one of those feasts will be moved to Monday
after Divine Mercy Sunday.

Best regards, and God bless you with this project.

Jacek Roszkowski

2015-12-17 9:41 GMT+01:00 pejulian <notifications@github.com>:

**Comment by pejulian** [comment]
Hi Jacek,

Thank you for the clarifications! 
I will add them into the national calendar for Poland.

It would be great also if you would like to collaborate further on this module in any way to improve its usability people. Or perhaps you may have ideas for other features. Just drop me a mail and we can work from there :+1: 


God bless,
Julian Pereira

**Pull request closed without merging**
