### PR TITLE
fix(util): fix `toScreamingSnakeCase()` function

### PR DESCRIPTION
**Pull request by tukusejssirs**
At the same time, create a test for the function.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
The following tests fail. Yes, it is unlikely we would run this function like this, but still the function is faulty.

```js
toScreamingSnakeCase('Some RandOm strinG') === 'SOME_RAND_OM_STRIN_G'  // Not: 'PAYAS _ASD_DS ASD'
toScreamingSnakeCase('Some RandOm') === 'SOME_RAND_OM'  // Not: 'PAYAS _ASD_DS'
toScreamingSnakeCase('Some  RandOm') === 'SOME_RAND_OM'  // Not: 'PAY  _ASD_DS'
toScreamingSnakeCase('thisIsAnExample') === 'THIS_IS_AN_EXAMPLE'  // Not: 'THIS_IS_ANEXAMPLE'
toScreamingSnakeCase('test_') === 'TEST'  // Not: 'TEST_'
```

I have just noticed you have created `monorepo` branch—thanks for sharing it with us! :pray: I didn’t have time yet to delve into it, however, I have noticed that there is not `string.spec.ts`. I’d like to port this PR into that branch, but I want to know why that test file is missing from that branch. Thanks! :pray:

**Comment by emagnier** [comment]
Yes, it seems there is an issue in the regex. The monorepo branch you are mentioning is out of date, so do not consider it (I'll share something when things will be mature and functional, and FYI, I no longer use this function in my refactor).

**Comment by tukusejssirs** [comment]
> The monorepo branch you are mentioning is out of date

I’d like to see your work on romcal ASAP (yes, I understand that it might not be fully working yet). I’d like you to work on romcal in more open fashion (or at least let me access your private repo with the new romcal version). Granted, I cannot and don’t want to order you to do so, but I’d prefer looking at the code as you iterate through all the features (etc). To be honest, going through large refactors and reimplementations is quite hard (it was the same with `_F-TypeScript` and partially also with PR #169); that’s why I prefer creating a PR early when I work on anything. I also think that I could give you some comments that could lead to (finally) release `romcal@3` and it might not take so long. I maybe could even contribute the the codebase and relieve you from some maintenance burden. YMMV.

Thanks for all you do for romcal! :pray:

**Comment by emagnier** [comment]
Please bear with me, as it's not progressing as quickly as expected due to my limited free time. I have no intention of hiding anything, and I prefer to take the time to test and solidify my ideas before presenting them publicly. 

My goal is to facilitate onboarding and future contributions to this project (with clear guidelines, tooling and documentation), with a final release in sight. In the meantime, I don't want to share something that isn't mature or stable in terms of architectural orientation (as it would end up wasting both of our time). 

FYI, I plan to present (hopefully very soon) some design notes from a few outcomes of my experiences, which will allow us to refine and discuss these topics further. 

Thank you for your understanding and patience.

**Review by TobiTenno — APPROVED** [review]

**Comment by TobiTenno** [comment]
@tukusejssirs what else were we looking for on this, still? can I assist in getting this part rebased and merged and the monorepo rebased once we get most of these PRs merged?

**Comment by tukusejssirs** [comment]
> what else were we looking for on this, still? can I assist in getting this part rebased and merged and the monorepo rebased once we get most of these PRs merged?

Well, I think it is good as it is, however, we could add more tests of the function. :thinking:

**Comment by tukusejssirs** [comment]
@TobiTenno, what should we do with special characters? Should we remove them? :thinking:

Currently, the following test passes:

```ts
it('should ???', () => {
  expect(toScreamingSnakeCase('123!@#$%^&*()こんにちは')).toBe('123!@#$%^&*()こんにちは');
});
```

**Comment by tukusejssirs** [comment]
Actually, we also should add a `util` scope (or something similar) to Commitlint config, probably in a separate PR.

**Comment by TobiTenno** [comment]
[re: @tukusejssirs]
> Actually, we also should add a `util` scope (or something similar) to Commitlint config, probably in a separate PR.

I think the commit you have that's failing commitlint should just be a `test`-typed commit.

**Comment by TobiTenno** [comment]
[re: @tukusejssirs]
> @TobiTenno, what should we do with special characters? Should we remove them? 🤔
> 
> Currently, the following test passes:
> 
> ```ts
> it('should ???', () => {
>   expect(toScreamingSnakeCase('123!@#$%^&*()こんにちは')).toBe('123!@#$%^&*()こんにちは');
> });
> ```

What would be the rationale for removing them? I don't know that I understand the issue with that test passing, primarily due to not knowing katakana.

**Comment by tukusejssirs** [comment]
> I think the commit you have that's failing commitlint should just be a test-typed commit.

I don’t think so, as in this PR, I am fixing a function in the first place. I created the test to verify the functionality of the function, i.e. to make sure the updated function behaves as expected.

IMHO we should always add tests and documentation (when it makes sense) in the same PR as the added/updated code, and not in a separate PR. `test` scope should be IMHO used only if we add tests or update faulty tests without modifying the tested code. YMMV.

> What would be the rationale for removing them? I don't know that I understand the issue with that test passing, primarily due to not knowing katakana.

`toScreamingSnakeCase` function is used to dynamically generate constants for some types, for example:

https://github.com/romcal/romcal/blob/3f7eb43cd47a2fa9ef1fc145e96e3d4ab8072615/lib/constants/periods.ts#L19-L21

This is used in multiple places. That said, it might be safe to tell that all usages of this function should be removed (even Etienne [said](https://github.com/romcal/romcal/pull/438#issuecomment-1546596906) that he _no loger use[s] this function in [his] refactor_).

The intention of the PR is to make sure the function behaves as expected, regardless of what we stuff into it.

**Comment by TobiTenno** [comment]
for the whole PR, yes, i was meaning specifically for the test addition. I was reading it as just being that. apologies for me mistaking your force push for a non-squash.

I understand that we coould just leave this entire PR off, but if it helps us refine our configs as we go, I'd like to get this and the util scope merged 👍

**Comment by tukusejssirs** [comment]
> for the whole PR, yes, i was meaning specifically for the test addition. I was reading it as just being that. apologies for me mistaking your force push for a non-squash.

Sorry, I prefer force-pushing changes in order to keep my PR commits clean (as there is a way on GitHub to see what the changes in the force-pushed commit). I usually always (re-) review all changes and mark files I reviewed using the dedicated checkbox. Thus I have never used the `Compare` button at the commits in the convo timeline. :man_shrugging: YMMV.

Anyway, no problem. :wink:

> I understand that we coould just leave this entire PR off, but if it helps us refine our configs as we go, I'd like to get this and the util scope merged 👍

IMO this PR is just what it is: a fix of a function that most probably will be removed in the futures + tests of that function. Thus this PR might be considered unnecessary, thus I’d be okay if you reject this PR.

On the other hand, the `util` scope is necessary IMO, as there is no other scope that could be used in its place, thus I’d really like to have that PR merged. :wink:

**Comment by TobiTenno** [comment]
oh, agreed. I haven't merged it yet cause i'm worried about releases not going through properly, but it's a style anyway, so should be ok

**Pull request merged**
