### PR TITLE
feat: fix es translation vincent_de_paul_priest is not bishop

### PR DESCRIPTION
**Pull request by miguelms95**
vincent_de_paul_priest is not bishop, fix es translation

### CODE REVIEW

**Comment by miguelms95** [comment]
@tukusejssirs @emagnier new PR, small fix for a translation in spanish

**Comment by TobiTenno** [comment]
thanks! looks like you need to amend your commit message, you'll probably want

`fix(es): vincent_de_paul_priest is not bishop`

**Comment by tukusejssirs** [comment]
Thanks, @miguelms95! The PR is alright, however, as @TobiTenno has already mentioned it, you need to change the commit message.

Do you need help with it? Should we do it? It is not a big deal we just try to use the same commit message format in every commit. :wink:

---

@TobiTenno, I thought Husky would take care of the commit messages and throw an error when an incorrect one is used. In my case it does work as expected:

```bash
gcl git@github.com:romcal/romcal.git
cd romcal
npm i  # Or: `pnpm i`
touch asdf
git add asdf
git commit -m 'asdf'

# The output of `git commit -m 'asdf'`:
Running PRE-COMMIT hook
→ No staged files match any configured task.
Running COMMIT MESSAGE hook
⧗   input: asdf
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/romcal/romcal/blob/dev/docs/contribute-to-romcal.md#committing-changes
```

I have tested it with NPM and PNPM. I did not run `pnpm prepare` / `npm run prepare`, it should not be required any more.

**Review by tukusejssirs — APPROVED** [review]

**Comment by TobiTenno** [comment]
@tukusejssirs that's assuming husky is installed (that's why we have the ci check) cause you can edit without installing deps, like from the web ui

**Comment by TobiTenno** [comment]
little cool note, refined github has started showing the fix/bug/etc tags in the commit tree so you can see what commits are tagged as 🆒 

image

**Comment by tukusejssirs** [comment]
@TobiTenno, well, I cannot confirm this. Maybe they rolled it out in the US first/only.

image

**Comment by TobiTenno** [comment]
Ah, [refined GitHub](https://github.com/refined-github/refined-github), it's a browser plugin

**Comment by TobiTenno** [comment]
@tukusejssirs do you wanna go ahead and rebase for him? i'm at work so i can't do this one

**Pull request merged**
