### PR TITLE
Add Jest snapshots to test romcal computed data

### PR DESCRIPTION
**Pull request by emagnier**
Add Jest snapshots, that test computed data on Liturgical/Gregorian calendars (over 3 consecutive years).

### CODE REVIEW

**Comment by emagnier** [comment]
FYI I've extracted this specific part (Jest snapshots) from https://github.com/romcal/romcal/pull/401, to get this improvement faster in the romcal codebase, and this test ready for next PRs.

**Comment by tukusejssirs** [comment]
@emagnier, why do we need to keep the snapshots in the codebase?

Otherwise, LGTM! :pray:

**Comment by emagnier** [comment]
Snapshots are an easy way to compare a bunch of computed data, and detect quickly if something is broken after a codebase update.

That's why it's important to have them in the git history, and to be able to update them if something has changed.

**Review by tukusejssirs — APPROVED** [review]

**Comment by emagnier** [comment]
@tukusejssirs, just a last point (if you agree), we do have both access to the merge button. As soon as a PR is approved, we could leave the merge action to the author of the PR (except if neither of us gave any sign of life after several days, or this PR is blocking for another PR).

**Comment by tukusejssirs** [comment]
> @tukusejssirs, just a last point (if you agree), we do have both access to the merge button. As soon as a PR is approved, we could leave the merge action to the author of the PR (except if neither of us gave any sign of life after several days, or this PR is blocking for another PR).

Yeah, you’re right. Sorry for merging the PR.

It makes sense, thus I do agree to this!

**Comment by emagnier** [comment]
No probs at all 👍. Thanks for your feedback!

**Pull request merged**
