### PR TITLE
Separate celebrations and fix some l10n issues

### PR DESCRIPTION
**Pull request by tukusejssirs**
- Separate multiple celebrations occuring on the same day;
- Rename `saintJeanVianneyTheCureOfArsPriest` to `saintJohnMaryVianneyPriest` ([source](http://www.liturgyoffice.org.uk/Calendar/2020/Aug.shtml));
- Rename `saintLouisGrignonDeMontfortPriest` to `saintLouisMarieGrignionDeMontfortPriest` ([source](http://www.liturgyoffice.org.uk/Calendar/2020/Apr.shtml));
- Rename `saintsJeanDeBrebeufAndIsaacJoguesPriestsAndCompanionsMartyrsSaintPaulOfTheCrossPriest` to `saintsJeanDeBrebeufAndIsaacJoguesPriestsAndCompanionsMartyrs` in `enCa.ts`;
- Rename `saintElizabethOfHungary` to `saintElizabethOfHungaryReligious`;
- Rename `saintPothinusBishopSaintBlAndinaVirginAndTheirCompanionsMartyrs` to `saintPothinusBishopSaintBlandinaVirginAndTheirCompanionsMartyrs` (note the casing of _Blandina_);
- Fix the celebrations on 11 November in `england.ts` (St Hilda and St Hugh of Licoln were somehow deleted in the calendar definition);
- Fix the `saintLouisMarieGrignionDeMontfortPriest` celebration definition ([source](https://en.wikipedia.org/wiki/General_Roman_Calendar#Australia));
- Fix some key values in `sk.ts`;
- Remove `saintHedwigOfSilesia` in favour of `saintHedwigReligious`;
- Remove `saintColumba`, `saintColumbaAbbotAndMissionary` and `saintColumbaColumCilleAbbot` in favour of `saintColumbaAbbot`;
- Remove `saintColumbanReligious` in favour of `saintColumbanAbbotAndMissionary`;
- Remove unnecessary commas in JSON before closing curly brackets in l10n files.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
Notes:

Below is a list of all keys that I have separated in this commit. First I list the old key, followed by its alternative key names (in the next line as a comment) if available, and finally the new keys (these are indented).

Also note that if a locale did not have the key tranlated yet, I did not create a new key.

<details>
   <summary>old and new keys</summary>

```bash
blessedBoleslawaMariaLamentVirginAndSaintAngelaMericiVirgin
  blessedBoleslawaMariaLamentVirgin
  saintAngelaMericiVirgin
saintAdalbertBishopAndMartyrSaintFidelisOfSigmaringenPriestAndMartyr
  saintAdalbertBishopAndMartyr
  saintFidelisOfSigmaringenPriestAndMartyr
saintBarbaraVirginAndMartyrOrBlessedAdolphKolpingPriest
  saintBarbaraVirginAndMartyr
  blessedAdolphKolpingPriest
saintBedeTheVenerablePriestAndDoctorSaintGregoryViiPopeSaintMaryMagdaleneDePazziVirgin
  saintBedeTheVenerablePriestAndDoctor
  saintGregoryViiPope
  saintMaryMagdaleneDePazziVirgin
saintClementIPopeAndMartyrSaintColumbanReligious
  saintClementIPopeAndMartyr
  saintColumbanReligious
saintDenisAndCompanionsMartyrsSaintJohnLeonardiPriest
  saintDenisAndCompanionsMartyrs
  saintJohnLeonardiPriest
saintDenisAndCompanionsMartyrsSaintJohnLeonardiPriestBlessedJohnNewmanBishop
  saintDenisAndCompanionsMartyrs
  saintJohnLeonardiPriest
  blessedJohnNewmanBishop
saintSixtusIiPopeAndCompanionsMartyrsSaintCajetanPriest
  saintSixtusIiPopeAndCompanionsMartyrs
  saintCajetanPriest
saintDominicPriest/SaintSixtusIiPopeAndCompanionsMartyrsSaintCajetanPriest
  saintDominicPriest
  saintSixtusIiPopeAndCompanionsMartyrs
  saintCajetanPriest
saintElizabethOfHungarySaintHildaAbbessSaintHughOfLincolnBishop
  saintElizabethOfHungaryReligious  # and delete saintElizabethOfHungary
  saintHildaAbbess
  saintHughOfLincolnBishop
saintEusebiusOfVercelliBishopSaintPeterJulianEymardPriest
  saintEusebiusOfVercelliBishop
  saintPeterJulianEymardPriest
saintGeorgeMartyrSaintAdalbertBishopAndMartyr
  saintGeorgeMartyr
  saintAdalbertBishopAndMartyr
saintHubertOfLiegeBishopOrSaintPirminAbbotAndBishop
  saintHubertOfLiegeBishop
  SaintPirminAbbotAndBishop
saintJohnSarkanderPriestAndMartyrSaintZdzislawa
  saintJohnSarkanderPriestAndMartyr
  saintZdzislawa
saintLouisSaintJosephOfCalasanzPriest
  saintLouis
  saintJosephOfCalasanzPriest
saintMargaretOfScotlandSaintGertrudeTheGreatVirgin
  saintMargaretOfScotland
  saintGertrudeTheGreatVirgin
saintPaulinusOfNolaBishopSaintsJohnFisherBishopAndThomasMoreMartyrs
  saintPaulinusOfNolaBishop
  saintsJohnFisherBishopAndThomasMoreMartyrs
saintPeterChanelPriestAndMartyrSaintLouisGrignonDeMontfortPriest
  saintPeterChanelPriestAndMartyr
  saintLouisMarieGrignionDeMontfortPriest  # and delete saintLouisGrignonDeMontfortPriest
saintsJeanDeBrebeufAndIsaacJoguesPriestsAndCompanionsMartyrsSaintPaulOfTheCrossPriest
  saintsJeanDeBrebeufAndIsaacJoguesPriestsAndCompanionsMartyrs
  saintPaulOfTheCrossPriest
saintsNereusAndAchilleusMartyrsSaintPancrasMartyr
  saintsNereusAndAchilleusMartyrs
  saintPancrasMartyr
saintWenceslausMartyrSaintLawrenceRuizAndCompanionsMartyrs
  saintWenceslausMartyr
  saintLawrenceRuizAndCompanionsMartyrs
blessedSanchaAndMafaldaVirginsOrBlessedTheresaOfPortugalReligious
  blessedSanchaAndMafaldaVirgins
  blessedTheresaOfPortugalReligious
mostHolyNameOfJesusOrOurLadyOfBethlehem
  theMostHolyNameOfJesus
  ourLadyOfBethlehem
ourLadyOfPerpetualHelpOrBlessedLeonidFeodorovPriestAndMartyr
  ourLadyOfPerpetualHelp
  blessedLeonidFeodorovPriestAndMartyr
saintBlaseBishopOrMartyrSaintAnsgarBishop
# or saintBlaseBishopAndMartyrSaintAnsgarBishop
  saintBlaseBishopAndMartyr
  saintAnsgarBishop
saintCamillusDeLellisPriestOrSaintHenryBishopAndMartyr
  saintCamillusDeLellisPriest
  saintHenryBishopAndMartyr
saintEdmundOfAbingdonBishopOrSaintMargaretOfScotland
  saintEdmundOfAbingdonBishop
  saintMargaretOfScotland
saintEphraemDeaconDoctorOrSaintColumbaColumCilleAbbot
  saintEphremDeaconAndDoctor
  saintColumbaColumCilleAbbot
saintHedwigReligiousOrSaintMargaretMaryAlacoqueVirgin
# or saintHedwigReligiousSaintMargaretMaryAlacoqueVirgin
  saintHedwigReligious  # and delete saintHedwigOfSilesia
  saintMargaretMaryAlacoqueVirgin  # and delete saintMargaretMaryAlacoque
saintJohnDamascenePriestAndDoctorOrSaintBarbaraVirginAndMartyr
  saintJohnDamascenePriestAndDoctor
  saintBarbaraVirginAndMartyr
saintLaurenceWangBingAndCompanionsMartyrsSaintJosephFreinademetzPriest
# or saintLaurenceWangBingAndCompanionsMartyrs
# or saintLaurenceWangBingAndCompanionsMartyrSaintJosephFreinademetzPriest
  saintLaurenceWangBingAndCompanionsMartyrs
  saintJosephFreinademetzPriest
saintLeoIxPopeOrBlessedMarcelCalloMartyr
  saintLeoIxPope
  blessedMarcelCalloMartyr
saintMuiredachBishopSaintAttractaVirginOrSaintLeliaVirgin
  saintMuredachBishop  # note that Muredach’s name is written without `i`
  saintAttractaVirgin
  saintLeliaVirgin
saintVincentDeaconAndMartyrOrSaintMarianneCopeVirgin
  saintVincentDeaconAndMartyr
  saintMarianneCopeVirgin
saintJeromeEmilianiSaintJosephineBakhitaVirgin
  saintJeromeEmiliani
  saintJosephineBakhitaVirgin
```
</details>

I did my best not to create duplicate keys (even duplicates with different key names, like the `saintHedwigOfSilesia` and `saintHedwigReligious`), but I might have missed some of them.

---

I also hope that I did not miss any titles (like a meta definition of martyr title for a non-martyr).

---

On `saintsJeanDeBrebeufAndIsaacJoguesPriestsAndCompanionsMartyrs` in `enCa.ts`: I think that l10n files should not contain _content_ differences, only _linguistic_ and _localisanional_ differences. The difference between this key defined in `en.ts` and `en-CA.ts` is in the patronage (additional titles), which IMO should be added to the particular celebration in `canada.ts` calendar. This is easily fixable as soon as the particular titles are added to `src/constants/Titles.ts` (see #182).

---

I suggest to replace `Doctor` with `Doctor of the Church` as the [Liturgy Office of England and Wales](http://www.liturgyoffice.org.uk/Calendar/2020/Apr.shtml) uses.

---

On `saintColumbaAbbot` and `saintColumbanAbbotAndMissionary`: There have been 5 keys for these two saints. I have chosen to use the celebration names form the Liturgy Office of England and Wales and removed the duplicates.

---

On trailing commas in JSON: AFAIK, there should never be a comma before closing bracket (any type of bracket) in JSON. For more info, here’s a nice [StackOverflow question](https://stackoverflow.com/questions/201782/can-you-use-a-trailing-comma-in-a-json-object).

---

I did not run `npm run prettier:check` for I have encountered the following error (and I wanted to push the code finally):

```bash
$ npm install prettier:check
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "prettier:": prettier:check

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ts/.npm/_logs/2020-03-07T23_26_33_979Z-debug.log
```

I even tried to install it via `npm install prettier prettier-check`, but it did not help.

**Comment by pejulian** [comment]
LGTM!

Some comments:

> On trailing commas in JSON: AFAIK, there should never be a comma before closing bracket (any type of bracket) in JSON. For more info, here’s a nice StackOverflow question.

The inclusion of trailing commas before closing brackets was done by `prettier` in accordance to [this rule](https://prettier.io/docs/en/options.html#trailing-commas) defined [here](https://github.com/romcal/romcal/blob/c7c46162275c6f7fb14bc2cccd354c6c861c1320/.prettierrc#L3).

> I did not run npm run prettier:check for I have encountered the following error (and I wanted to push the code finally):

`prettier:check` is a custom script that I defined [here](https://github.com/romcal/romcal/blob/c7c46162275c6f7fb14bc2cccd354c6c861c1320/package.json#L27) for convenience sake so that we do not have to repeatedly type out the full command every time we want to run `prettier` related operations on the code.

The script uses the `prettier` npm package to function. For this script to run properly, simply run `npm install` in the root directory of `romcal` and all should be good.

**Comment by emagnier** [comment]
Nice work!

To run prettier from the root dir of romcal:
```
npx prettier --write src/**/*.ts
```

But to make that easiest from the terminal, we should consider adding a new npm task in the `package.json`, something like `npm run format` that will do the same thing.

**Comment by pejulian** [comment]
> Nice work!
> 
> To run prettier from the root dir of romcal:
> 
> ```
> npx prettier --write src/**/*.ts
> ```
> 
> But to make that easiest from the terminal, we should consider adding a new npm task in the `package.json`, something like `npm run format` that will do the same thing.

We already do 😄 

`npm run prettier:check`: Tells you what's wrong with the code and where...
`npm run prettier:fix`: Attempts to fix these errors for good...

Ideally, we shouldn't need to use `npx` because we already have the tooling as part of `devDependencies` in `romcal`.

**Comment by emagnier** [comment]
You are right, I didn't see that `prettier` tasks are already in the package.json.

**Comment by tukusejssirs** [comment]
> `prettier:check` is a custom script that I defined here for convenience sake so that we do not have to repeatedly type out the full command every time we want to run `prettier` related operations on the code.

Oh, thanks!

Anyway, this should be noted in the _Contributor’s guide_ (or a sub-document) in the docs, something like this:

> You may want to check if there are files that are not compliant with our `.prettierrc.js` settings and to fix them. For this you may use the following commands in the `romcal` repo:
> 
> ```bash
> # First, you need to install romcal from source (run this in the romcal repo root)
> npm install
> 
> # Outputs any non-compliant files in the repo
> npm run prettier:check
> 
> # Fixes all non-compliant files
> npm run prettier:fix
> ```

And I’d like to see the diff of the style issues, something like `git diff` produces. Is this implemented in the script yet?

> The inclusion of trailing commas before closing brackets was done by `prettier` in accordance to [this rule](https://prettier.io/docs/en/options.html#trailing-commas) defined [here](https://github.com/romcal/romcal/blob/c7c46162275c6f7fb14bc2cccd354c6c861c1320/.prettierrc#L3).

I agree with you that we should do it via script, not by hand.

And I suggest to use `none` value for the trailing comma setting (for I think it should comply with strict JSON specification, although as you say, technically it is written in TS, so it works even with trailing commas), but I am not the one who should make this kind of decisions.

**Comment by emagnier** [comment]
The `all` value for trailing comma is also giving us some convenient usages when we write code, and it makes a cleanest git history when we just add a property at the end of an object (we don't have to add/manage the missing comma in the line above).

**Comment by tukusejssirs** [comment]
@emagnier, I see what mean, but I’d still use `none`. However, do as you wish and think it is the best! :smiley:

**Comment by tukusejssirs** [comment]
@pejulian, @emagnier, back to the topic: Should I fix the style in a commit or will you do it as part of the merge?

**Comment by pejulian** [comment]
My suggestion would be to get prettier up and running in your machine so that you can run the scripts to automatically fix the code. I too vote to keep trailing commas to “all” for the same reasons @emagnier has outlined.

**Comment by tukusejssirs** [comment]
> My suggestion would be to get prettier up and running in your machine so that you can run the scripts to automatically fix the code. I too vote to keep trailing commas to “all” for the same reasons @emagnier has outlined.

Okay. :smiley:

**Comment by pejulian** [comment]
@tukusejssirs,

Sorry, I wrongly typed out my thoughts to your question. My bad.

I *will* go ahead and perform the merge because functionally, there's nothing further to change in the code. The linting issues will be fixed as part of the merge. What I meant was for you to get `prettier` up and running properly in your machine for future use 😄

**Comment by pejulian** [comment]
> You are right, I didn't see that `prettier` tasks are already in the package.json.

No worries! There's a little of this and that hanging around the code that hasn't been documented yet. The documentation updates in #181 should cover all these new features.

**Pull request merged**
