### PR TITLE
Add locale for spanish

### PR DESCRIPTION
**Pull request by CodingAleCR**
Hi, I saw this and wanted to add the spanish translations for this. I saw that in #189 there was a small discussion on whether to make the PR to master or to the Typescript branch. Let me know if the branch is far ahead than what it was a couple of months ago and if the PR should be adjusted or if you would prefer two different PRs (one to master and one to Typescript branch). Cheers from Costa Rica 🇨🇷!

### CODE REVIEW

**Comment by tukusejssirs** [comment]
Hey, @CodingAleCR! Thanks for the PR!

Indeed, the PR should be updated on top of the `_F-TypeScript` branch.

And although not obligatory (at least from @emagnier point of view), it would be awesome if you translate all the keys from `src/locales/en.ts` file into Spanish. Yes, it might take you some time and you would need to search for some lesser known saints/blesseds (esp those not celebrated in Spanish speaking countries), but it might be useful when viewing calendars with those saints/blesseds in Spanish locale. But yes, that might be dealt with in another PR.

Also it might be a good idea to review the `src/calendars/costaRica.ts` calendar if it is corrent. Maybe you already did that. :smiley:

And just a note: although it not fully in accord with the [JSON standard](https://www.json.org/json-en.html), we use the final trailing commas at the end of the key values, as you can see in [`en.ts` L788-789](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/en.ts#L788). Also note that in that branch, everywhere we use single quotes.

And it might a good idea to use [`.editorconfig`](https://editorconfig.org/), because e.g. you have removed the final trailing newline from the `es.js` file. And we use 2 spaces for indentation. However, all of this would be fixed by using `.editorconfig` settings.

And a final note: current code cannot be just copied over to the `_F-TypeScript` branch, as we have modified some keys. Also the syntax has been changed a bit (like the keys are not quoted anymore and we are importing `RomcalLocale` at the beginning. Take you time to update the PR.

And once again, thank you for your time to create this PR! :+1:

**Comment by emagnier** [comment]
Awesome Alejandro! Your work is a very nice addition, thanks a lot!

We are currently working on a major refactor and the Typescript branch isn't ready yet. But no worries, I'll take care of merging your work in the good branch. I'll do a quick review tomorrow or Thursday, so your work will be merged ASAP!

**Comment by CodingAleCR** [comment]
> Hey, @CodingAleCR! Thanks for the PR!
> 
> Indeed, the PR should be updated on top of the `_F-TypeScript` branch.
> 
> And although not obligatory (at least from @emagnier point of view), it would be awesome if you translate all the keys from `src/locales/en.ts` file into Spanish. Yes, it might take you some time and you would need to search for some lesser known saints/blesseds (esp those not celebrated in Spanish speaking countries), but it might be useful when viewing calendars with those saints/blesseds in Spanish locale. But yes, that might be dealt with in another PR.
> 
> Also it might be a good idea to review the `src/calendars/costaRica.ts` calendar if it is corrent. Maybe you already did that. 😃
> 
> And just a note: although it not fully in accord with the [JSON standard](https://www.json.org/json-en.html), we use the final trailing commas at the end of the key values, as you can see in [`en.ts` L788-789](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/en.ts#L788). Also note that in that branch, everywhere we use single quotes.
> 
> And it might a good idea to use [`.editorconfig`](https://editorconfig.org/), because e.g. you have removed the final trailing newline from the `es.js` file. And we use 2 spaces for indentation. However, all of this would be fixed by using `.editorconfig` settings.
> 
> And a final note: current code cannot be just copied over to the `_F-TypeScript` branch, as we have modified some keys. Also the syntax has been changed a bit (like the keys are not quoted anymore and we are importing `RomcalLocale` at the beginning. Take you time to update the PR.
> 
> And once again, thank you for your time to create this PR! 👍

Thanks for the [`.editorconfig`](https://editorconfig.org/) tip, will check it and apply the needed fixes. I will check on Costa Rica's calendar but I will do it separately to avoid mixing it up with the translation and for sure put another PR for it. Thanks a lot for the suggestions @tukusejssirs.

**Comment by tukusejssirs** [comment]
As for the `.editorconfig` you should not need to edit the files manually (as you seamingly did in your last commit); you should use an editor (with `.editorconfig` plugin if needed; see the [`.editorconfig` website](https://editorconfig.org/#download) for more info) and simply re-save it.

I have just noticed that you sometimes use `el apóstol` with `el` article, sometimes without it. Although my knowledge of Spanish is absolutely minimal, I have found the liturgical calendar for Costa Rica at [vercalendario.info](https://www.vercalendario.info/es/evento/liturgia-catolica-ano-calendario-2019.html), which also uses `el apóstol` both with and without the article. It might a good idea to get the _official_ directory / liturgical calendar (which should be published annually) or other official liturgical books (like the _Roman Missal_), but those might be a bit out of date as the celebrations might be moved/removed/changed since the publication date of those books.

However, even if the official books / directory / liturgical calendar should be inconsistent, I would suggent you to be consistent and set (yourself) some rules you would keep. Also you could contact the Liturgical Commision of your diocese and/or country to be more consistent.

And if you know of some linguistic differences in the Spanish Spanish as opposed to Costarican Spanish, you should keep the Spanish Spanish in `es.ts` and the changes (and only them) for Costarican Spanish in `es-CR.ts`. Take for example the spelling differences in the American and British Englishes: `Savior` would go into `en.ts` and `Saviour` into `en-GB.ts`.

Anyway, why do you (and that website sometimes use `santo` and sometimes `san` for one single male saint? Like in `Santo Tomás el Apóstol` and `San Antonio Zaccaria, el sacerdote`. I’m just curious. Actually, you don’t translated St Anthony Zaccaria. :smiley: I suggest you to copy `en.ts` fo `es.ts` and translate all the strings into Spanish. If you choose to not translate celebration names for celebrations that are not celebrated in Costa Rica, that you should remove those lines from the code.

**Comment by CodingAleCR** [comment]
> As for the `.editorconfig` you should not need to edit the files manually (as you seamingly did in your last commit); you should use an editor (with `.editorconfig` plugin if needed; see the [`.editorconfig` website](https://editorconfig.org/#download) for more info) and simply re-save it.
> 

Yes, what happened was that my latest commit was fixing a minor mistake I did while installing the plugin for VSCode.

> I have just noticed that you sometimes use `el apóstol` with `el` article, sometimes without it. Although my knowledge of Spanish is absolutely minimal, I have found the liturgical calendar for Costa Rica at [vercalendario.info](https://www.vercalendario.info/es/evento/liturgia-catolica-ano-calendario-2019.html), which also uses `el apóstol` both with and without the article. It might a good idea to get the _official_ directory / liturgical calendar (which should be published annually) or other official liturgical books (like the _Roman Missal_), but those might be a bit out of date as the celebrations might be moved/removed/changed since the publication date of those books.
> 
> However, even if the official books / directory / liturgical calendar should be inconsistent, I would suggent you to be consistent and set (yourself) some rules you would keep. Also you could contact the Liturgical Commision of your diocese and/or country to be more consistent.

Whenever we use 'el' in the case of apostles we use it when there's no comma in between, I'll probably change them all to use the comma since it's what we mostly use in spanish.

> And if you know of some linguistic differences in the Spanish Spanish as opposed to Costarican Spanish, you should keep the Spanish Spanish in `es.ts` and the changes (and only them) for Costarican Spanish in `es-CR.ts`. Take for example the spelling differences in the American and British Englishes: `Savior` would go into `en.ts` and `Saviour` into `en-GB.ts`.

Yep, in spanish there's not that much of a difference at least regarding the roman calendar since we were all related to Spain at one point or another, that's why I didn't go with creating the `es-CR.ts`, I think I might even have to check out guides on the difference to be honest, lol

> Anyway, why do you (and that website sometimes use `santo` and sometimes `san` for one single male saint? Like in `Santo Tomás el Apóstol` and `San Antonio Zaccaria, el sacerdote`. I’m just curious.

As a language rule we use `santa` for all saints that are women, we use `san` for all saints that are men excepting `Tomé, Toribio, Tomás, Domingo` which by rule we use `santo`. As a side note, `Santiago` does not need to be prepended with anything since the name already includes it. It's a weird language rule to be honest haha but yeah, that's why we use it.

> Actually, you don’t translated St Anthony Zaccaria. 😃 I suggest you to copy `en.ts` fo `es.ts` and translate all the strings into Spanish. If you choose to not translate celebration names for celebrations that are not celebrated in Costa Rica, that you should remove those lines from the code.

I tried to accomplish the same thing that was done for pt-BR but yeah, I started the job as a copy of `en.ts` but then proceeded to delete most of the celebrations that I have not seen been celebrated around our latin american countries and in Spain so I don't know if it's necessary to add them all. I did notice, however, that there's no key related to what we call `el Día de los Reyes Magos` or `Día de Reyes` which I don't know how it's called in English, I guess it would be (after googling a bit) something like `Three Kings Day`. This celebration is really important for spanish speaking countries so I don't know if there's a way to add it.

By the way, where did you get the hex color values for the liturgical colors? I've being searching for those for a while now 😮.

P.s: I fixed the usage of `el` according to how we commonly refer to those days during the celebration.

**Comment by tukusejssirs** [comment]
> Yep, in spanish there's not that much of a difference at least regarding the roman calendar since we were all related to Spain at one point or another, that's why I didn't go with creating the `es-CR.ts`

I was not talking the _calendars_, but about the language and the _celebration names_. Calendar and celebration differences (non-linguistic ones) should/will be dealt in `src/calendars/*.ts`.

> I think I might even have to check out guides on the difference to be honest, lol

If you're not sure, don't do anything with this. :smiley: I’d rather wait if any Spanish Spanish speaker would come in and then we’ll fix any issues. But when you _learn_ something, do it the proposed way. :smiley:

> As a language rule we use santa for all saints that are women, we use san for all saints that are men excepting Tomé, Toribio, Tomás, Domingo which by rule we use santo. As a side note, Santiago does not need to be prepended with anything since the name already includes it. It's a weird language rule to be honest haha but yeah, that's why we use it.

Thanks for the explanation. The way I get it, `san` is with male saints, unless the saint’s name with `-o` or `-é` or `-s`, right? I’m quite curious about `san/santo Tomás`, as [here](https://www.vercalendario.info/es/evento/liturgia-catolica-ano-calendario-2019.html) all Tomás are `santo` except for Tomás Moro—is that correct or is it a mistake? Again, you didn’t list St Thomas More listed in `es.js`, but the reason might be that we have a joint celebration key only (see [`en.ts` L697](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/en.ts#L697). If you miss a key for a celebration, you should create the key and it would be nice of you give us (me) a list of the added keys in order add then fo other languages (I personally would add them at least to `en.ts` and `sk.ts` if no one else do that). Anyway, it might be a good idea to double-check if all celebration keys (the celebration names) for all celebrations celebrated in CR are in `es.ts`.

> I tried to accomplish the same thing that was done for pt-BR

Well, from my point of view `pt-Br.ts`s quite incomplete (as far as I can tell, it contains
only celebrations celebrated in PT, which is sufficient for _some_ needs, but I think that translating all the keys to every (supported) language is better, becauce then anyone could generate any calendar in any locale (e.g. the Slovak calendar in Spanish), but I know that (1) one needs more time to translate all the keys; (2) there many people (like me) who would like to check liturgical calendars of other countries.

> then proceeded to delete most of the celebrations that I have not seen been celebrated around our latin american countries and in Spain so I don't know if it's necessary to add them all.

Well, if you do it that way, it’ll be better than nothing, but as I said above, it might be better to translate them all if you have the time (even if it would be in a separate PR).

> I did notice, however, that there's no key related to what we call el Día de los Reyes Magos or Día de Reyes which I don't know how it's called in English, I guess it would be (after googling a bit) something like Three Kings Day. This celebration is really important for spanish speaking countries so I don't know if there's a way to add it.

Three Kings celebration is officially called the Epiphany [of the Lord]. :smiley: Therefore it is on L14 of `es.js`. I hope you don’t have a separate celebration with that nams on a date diffedent from 6 January (or the Sunday following it)—I could find it [here](https://www.vercalendario.info/es/evento/liturgia-catolica-ano-calendario-2019.html) at least.

> By the way, where did you get the hex color values for the liturgical colors? I've being searching for those for a while now 😮.

I am not sure what exactly do you mean by _hex colours_, but AFAIK the colours aren’t defined in romcal apart from [`liturgical-colors.constant.ts`](https://github.com/romcal/romcal/blob/_F-TypeScript/src/constants/liturgical-colors.constant.ts). I think fhe exact colour code might be defined in [`romcal-api`](https://github.com/romcal/romcal-api) repo, but @emagnier might know better.

**Comment by CodingAleCR** [comment]
> I was not talking the calendars, but about the language and the celebration names. Calendar and celebration differences (non-linguistic ones) should/will be dealt in src/calendars/*.ts.

Oh, yeah, sorry. I was referring to the same thing but didn't explain myself well enough. 

> Thanks for the explanation. The way I get it, san is with male saints, unless the saint’s name with -o or -é or -s, right? I’m quite curious about san/santo Tomás, as here all Tomás are santo except for Tomás Moro—is that correct or is it a mistake? Again, you didn’t list St Thomas More listed in es.js, but the reason might be that we have a joint celebration key only (see en.ts L697. If you miss a key for a celebration, you should create the key and it would be nice of you give us (me) a list of the added keys in order add then fo other languages (I personally would add them at least to en.ts and sk.ts if no one else do that). Anyway, it might be a good idea to double-check if all celebration keys (the celebration names) for all celebrations celebrated in CR are in es.ts.

Kind of, so, here's the thing, you would only use `Santo` when you are using the specific names: Tomé, Toribio, Tomás, Domingo. I think the website you are using even uses it for one called `Charbel` which is a saint I've never heard of so I can't give the specifics on the why they do it.

> Three Kings celebration is officially called the Epiphany [of the Lord]. 😃 Therefore it is on L14 of es.js. I hope you don’t have a separate celebration with that names on a date different from 6 January (or the Sunday following it)—I could find it here at least.

Gotcha, yeah, then it should probably stay the same in spanish. I guess my confusion was due to the popular name that's been given to the celebration. You are correct on that.

> Well, from my point of view pt-Br.tss quite incomplete (as far as I can tell, it contains
only celebrations celebrated in PT, which is sufficient for some needs, but I think that translating all the keys to every (supported) language is better, becauce then anyone could generate any calendar in any locale (e.g. the Slovak calendar in Spanish), but I know that (1) one needs more time to translate all the keys; (2) there many people (like me) who would like to check liturgical calendars of other countries.

Oh, I understand, I will try to do that, although it's difficult with some names since there's no translation for them, do you suggest I leave those as is and just translate the 'saint' to 'san' accordingly?

> I am not sure what exactly do you mean by hex colours, but AFAIK the colours aren’t defined in romcal apart from liturgical-colors.constant.ts. I think fhe exact colour code might be defined in romcal-api repo, but @emagnier might know better.

What I meant to ask is, are those the official hex color values? Meaning, is that the standard liturgical colors for everything Church-related?

**Comment by tukusejssirs** [comment]
> Oh, I understand, I will try to do that, although it's difficult with some names since there's no translation for them, do you suggest I leave those as is and just translate the 'saint' to 'san' accordingly?

The way I did it for the Slovak locale (`sk.ts`) is that I searched the Internet if those names are already used somewhere _on a Slovak website_. If I did not find that name (which happened very rarely), I simply translated the first name into Slovak (which is kind of tradition coming from Latin) and for female saints added a suffix of `-ova` (which is a Slovak grammar rule). For the names like _St John of the Cross_ we need to translate the _of the Cross_ part too. In general, try to localise the names as naturally as possible and follow the way it is already done for other, similar names.

> What I meant to ask is, are those the official hex color values? Meaning, is that the standard liturgical colors for everything Church-related?

Aaah, sorry, I think you mean [`LiturgicalColors.js`](https://github.com/romcal/romcal/blob/master/src/constants/LiturgicalColors.js) from the `master` branch. I was talking about the Typescript branch, which does not have the hex colour codes.

1. There is no official shade of a particular colour that must be used.

2. I advise you to use the [`_F-TypeScript`](https://github.com/romcal/romcal/tree/_F-TypeScript) for development, where there are many (breaking) changes in comparison with the `master` and which will be released probably in August 2020.

**Comment by CodingAleCR** [comment]
Ok sounds great, I will try to do the full translation over the weekend.

Thanks for all the guide around this and the effort the team is making to improve this library! 🥳🎉

**Comment by emagnier** [comment]
Thanks for your contribution @CodingAleCR !
Yes if you feel confortable to work on the Spanish translation from the [_F-TypeScript](https://github.com/romcal/romcal/tree/_F-TypeScript), go for it 😉 

I'm currently planning to have a few days at the beginning of august dedicated to Romcal. So if all goes well, we could get a new release by the end of august, containing a major refactor and a switch to Typescript.

And about the liturgical colors, Romcal will output a color name only, because the General Instruction of the Roman Missal only recomnand a color, without any specific color code. Then you are free to use any hex color in your app, based on this name outputed by Romcal.

**Comment by emagnier** [comment]
Hola @CodingAleCR ! I took a quick look on your work and everything looks good 🍻! Although I'm not a Spanish speaking, I made 2 years of Spanish at school but it's been a long time ago now 😄 

Do you think you will have the time to adjust your PR on the Typescript branch? If it's possible, that would help us a lot. Otherwise I will try to do something during the next month.

And about translating everything in Spanish, I will say it's a nice to have, but not a priority. As far as we can have the necessary for most of the Spanish speaking calendars (this is the great job you already made). 
Having everything translated is only a requirement in English (for example, if you add a localisation key in Spanish, you will have to add it in English as well).

For the translation, calendars and keys in general, you can lean on @tukusejssirs, he is the keeper of all the localisation work!

**Comment by CodingAleCR** [comment]
Hi, yes, I will update it to point towards the Typescript branch, I have being waiting to see how it is implemented with the new PR that I just noticed was merged. I will also update the needed keys. What I was thinking, since it would take less time, was that I could translate the current keys and then add the missing ones in the future to have parity with english. I also found a couple of keys that I might add since they are common celebrations in spanish speaking countries.

**Comment by tukusejssirs** [comment]
> [@CodingAleCR]
> […] and then add the missing ones in the future to have parity with english. I also found a couple of keys that I might add since they are common celebrations in spanish speaking countries.

Just double-check if the celebrations actually aren’t in `en.ts` (they might be there with different key name/value. When unsure, rather ask us before you actually add a new key (just to remove any possibility of introducing yet another duplicate).

**Comment by CodingAleCR** [comment]
Will do, for example I wanted to add this one (https://en.wikipedia.org/wiki/Virgen_de_los_Angeles) which is roughly translated to Our Lady of the Angels. It is our patron here in Costa Rica but I have it on good authority that it is celebrated across Central America as well

**Comment by tukusejssirs** [comment]
Yeah, that one is indeed missing. And there are a few churches in the US with that patron (incl the Cathedral of Our Lady of the Angels).

I’ve noticed that you have written the first letter of the titles (like priest, doctor of the Church or virgin) in uppercase—is it really right that way?

**Comment by tukusejssirs** [comment]
@CodingAleCR, I have no idea if you have already started the l10n (I have not found any new code in your fork of romcal), but just now I have found a quite good source of Spanish names of the lesser known saints and blessed: [Martirologio Romano (2001)](http://www.diocesisdecanarias.es/downloads/santosmartirologiojuliodiciembre.pdf). It is a Spanish translation of the original _Martyrologium Romanum_ from 2001, which is written in Latin. How much it is official and/or accurate, I cannot tell.

There is a newer edition of MR, the MR2004 which is currently officially in Latin only and the [Wiki](https://en.wikipedia.org/wiki/Martyrology#Roman_Martyrology) says this about the differences between the two editions:

> After the Second Vatican Council, a fully revised edition was promulgated in 2001, followed in 2005 by a version (bearing the publication date of 2004) that adjusted a number of typographical errors that appeared in the 2001 edition and added 117 people canonized or beatified between 2001 and 2004, as well as a number of more ancient saints not included in the previous edition. "The updated Martyrology contains 7,000 saints and blesseds currently venerated by the Church, and whose cult is officially recognized and proposed to the faithful as models worthy of imitation."

**Comment by CodingAleCR** [comment]
Wow, that's a great find, I have started the work but have not pushed to the repo, I'll try to compliment and verify translations with that resource. Do you plan using it for Latin translations?

**Comment by tukusejssirs** [comment]
You might push your work to the repo and than change the branch in this PR. That way we might see some progress (see #207 PR, where I push a new commit each day I work on it); the commits will be squashed before merging.

>  Do you plan using it for Latin translations?

I’d like get the MR2004 and then use it as the base for the more comprehensive list of venerated persons. I’d like to use all the saints/blesseds feom MR2004, all the saints/blesseds addes since 2004, as well as saints/blesseds which are not in the MR2004, but they are celebrated at least in one particular calendar. But currently I have no access to it.

**Comment by tukusejssirs** [comment]
Just a note: the [MT2001_es](http://www.diocesisdecanarias.es/downloads/santosmartirologiojuliodiciembre.pdf) I have shared contains only months July to December; [here](https://diocesisdecanarias.net/wp-content/uploads/2015/08/santosmartirologioenerojunio.pdf) is the first part, i.e. January through June. :smiley:

**Comment by tukusejssirs** [comment]
And also suggest to keep an eye on #208 issue.

**Comment by CodingAleCR** [comment]
Alright, I will add my changes and change branch so you can make the suggestions we might need.

**Comment by tukusejssirs** [comment]
@CodingAleCR, could you please note down what sources have you used for the localisation (and later for the calendar of Costa Rica)? If you used online sources (publicly available), the URL is enough; if you used some printed books, some bibliographical metadata would be nice to have (at least book name, publisher and year). I’d like to create a list of validated calendars and locales. Thanks in advance.

**Comment by emagnier** [comment]
Hello @CodingAleCR, 

Instead of merging your PR into `master`, I've cherry-picked all your work from this PR to the `_F-TypeScript`: https://github.com/romcal/romcal/commit/2d6992f0a293c5aeee4277b7b29fbcb2587684a5

We are about to do a massive refactor of all locale keys, but we wanted to have all your work into our new TypeScript codebase. FYI, in a few days we plan to do a release of our new codebase in the `dev` branch.

Thanks again for all this nice work! 🎉 🎉 🚀 
If you made other work since that you didn't push yet, please let us know, and we will see how to integrate your work.

**Comment by CodingAleCR** [comment]
I'm sorry I didn't get to it in time, stuff's being crazy at work. Hope it helps out, I really do believe it's awesome what you people are doing 🙌🏼🎉

**Comment by emagnier** [comment]
No worries, thank you for your message 😉 
And Spanish locale makes a great addition for romcal!

**Comment by tukusejssirs** [comment]
@CodingAleCR, there are some keys which are not (fully) localised:

```js
saintBeunoAbbot: 'Saint Beuno, Abbot',  // This key is not localised at all
saintRomualdAbbot: 'Sant Romuald, Abbot',  // Sant or San? Abbot or Abad?
saintAlbanMartyr: 'Saint Alban, Mártir',  // Saint or San?
```

My another question is if in Spanish the titles (like abbot, priest, pope) in the celebration names are capitalised (i.e. the first letter is in uppercase) or not. I have the expression you tried to localise the English keys as faithfully as you could, however, I believe it would be better if you tried to be as faithful as possible the the _Spanish_ language.

Could you re-read [`es.ts`](https://github.com/romcal/romcal/blob/2d6992f0a293c5aeee4277b7b29fbcb2587684a5/src/locales/es.ts) please? I think there are more issues with the current version of `es.ts`.

**Comment by CodingAleCR** [comment]
So, according to the RAE (biggest authority regarding the Spanish language) with titles, particularly the ones we are using here ("abad"-abbot, "presbítero"-priest, "papa"-pope) can be written just fine in lowercase. I think I left most capitalized so they might need correction. 

The thing is that with Spanish, the proper way would be with lowercase. However, you sometimes can refer to those as capitalized out of respect, it's something called "mayúsculas genuflexivas". I would suggest using lowercase however just to comply with language rules.

**Comment by CodingAleCR** [comment]
So, according to the RAE (biggest authority regarding the Spanish language) with titles, particularly the ones we are using here ("abad"-abbot, "presbítero"-priest, "papa"-pope) can be written just fine in lowercase, especially in the cases that the word is used a lot in the text. However, you sometimes can refer to those as capitalized out of respect, it's something called "mayúsculas genuflexivas". 

Now, that rule changes a bit when we are referring to celebration names, whenever you are writing the name of a celebration, you should always write the substantives and adjectives in the name capitalized, this has to be done regardless of it being a civil, military or religious festivity.

**Comment by tukusejssirs** [comment]
> So, according to the RAE (biggest authority regarding the Spanish language) with titles, particularly the ones we are using here ("abad"-abbot, "presbítero"-priest, "papa"-pope) can be written just fine in lowercase, especially in the cases that the word is used a lot in the text. However, you sometimes can refer to those as capitalized out of respect, it's something called "mayúsculas genuflexivas".

Thanks for the answer. I have read [this Spanish article](https://periodistas-es.com/titulos-y-cargos-con-minuscula-inicial-23383) ([translated to English](https://translate.google.co.uk/translate?sl=es&tl=en&u=https%3A%2F%2Fperiodistas-es.com%2Ftitulos-y-cargos-con-minuscula-inicial-23383)) on those _mayúsculas genuflexivas_ (genuflective capital letters). It seems that the Spanish language at least prefers not using the _mayúsculas genuflexivas_. It seem to me as this practice is similar to English language, where is is grammatically correct the use `the Pope`, `the President` or `the Prime Minister` when talking about a particular person (it is incorrect to use `the pope` with lowercase letter, but `a pope` or `the popes` is correct).

It might a good idea to localise all titles (I have already created a list of them in a [Google Sheets table](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=24811360)) in order to help me correct this issue.

Another subissue: do you use uppercase first letter in names of Our Lady (e.g. Patroness, Medeatrix)?

> Now, that rule changes a bit when we are referring to celebration names, whenever you are writing the name of a celebration, you should always write the substantives and adjectives in the name capitalized, this has to be done regardless of it being a civil, military or religious festivity.

You mean you use title case in titles and heading of articles/books? Do you use similar title case rules to those defined by Chicago Manual of Style? The general rules are that all nouns, adjectives, pronounes, verbs, numbers are written with uppercase first letter and the last word of the title/heading is capitalised. Usually, the words with less than four letters are written in lowercase.

https://titlecaseconverter.com/

**Comment by CodingAleCR** [comment]
> > So, according to the RAE (biggest authority regarding the Spanish language) with titles, particularly the ones we are using here ("abad"-abbot, "presbítero"-priest, "papa"-pope) can be written just fine in lowercase, especially in the cases that the word is used a lot in the text. However, you sometimes can refer to those as capitalized out of respect, it's something called "mayúsculas genuflexivas".
> 
> Thanks for the answer. I have read [this Spanish article](https://periodistas-es.com/titulos-y-cargos-con-minuscula-inicial-23383) ([translated to English](https://translate.google.co.uk/translate?sl=es&tl=en&u=https%3A%2F%2Fperiodistas-es.com%2Ftitulos-y-cargos-con-minuscula-inicial-23383)) on those _mayúsculas genuflexivas_ (genuflective capital letters). It seems that the Spanish language at least prefers not using the _mayúsculas genuflexivas_. It seem to me as this practice is similar to English language, where is is grammatically correct the use `the Pope`, `the President` or `the Prime Minister` when talking about a particular person (it is incorrect to use `the pope` with lowercase letter, but `a pope` or `the popes` is correct).
> 
> It might a good idea to localise all titles (I have already created a list of them in a [Google Sheets table](https://docs.google.com/spreadsheets/d/1c9YWtfntpxy0r0rg0mfowJ2v-yKW6wSMmNzyY3umBU4/edit#gid=24811360)) in order to help me correct this issue.
> 
Yes, it could be a good idea, not sure if it's something you might want to abstract though since it might be more effort maintaining it.

> Another subissue: do you use uppercase first letter in names of Our Lady (e.g. Patroness, Medeatrix)?
> 
Yes we do, "Nuestra Señora", "Patrona",  "Mediadora", "Mother" are all used capitalized normally.

> > Now, that rule changes a bit when we are referring to celebration names, whenever you are writing the name of a celebration, you should always write the substantives and adjectives in the name capitalized, this has to be done regardless of it being a civil, military or religious festivity.
> 
> You mean you use title case in titles and heading of articles/books? Do you use similar title case rules to those defined by Chicago Manual of Style? The general rules are that all nouns, adjectives, pronounes, verbs, numbers are written with uppercase first letter and the last word of the title/heading is capitalised. Usually, the words with less than four letters are written in lowercase.
> 
> https://titlecaseconverter.com/

It's a little bit different than a title case, we do not capitalize articles used in the name of a festivity, for example: "Sacred Heart Of Jesus" is translated to "Sagrado Corazón **d**e Jesús". Same way we would not capitalize articles in Spanish like "la", "el", "de", "los", "sus" amongst others.

Also, I fixed the missing translations in #219.

**Comment by tukusejssirs** [comment]
> Yes, it could be a good idea, not sure if it's something you might want to abstract though since it might be more effort maintaining it.

Context: I have proposed to moved all titles from the l10n keys to the celebration definitions (i.e. calendars; see #201, #154 and #208), therefore in the end, we will (hopefully) remove the titles from the l10n keys.

Question: Why do you think that it might be more effort maintaining it?

> It's a little bit different than a title case, we do not capitalize articles used in the name of a festivity, for example: "Sacred Heart Of Jesus" is translated to "Sagrado Corazón **d**e Jesús". Same way we would not capitalize articles in Spanish like "la", "el", "de", "los", "sus" amongst others.

I (as many others, but not everybody) differentiate between _title case_ (sometimes called _true title case_) and _First Letter Uppercase_ (sometimes called _title case_). `Sacred Heart Of Jesus` is chiefly used in North America. However, Chicago Manual of Style says the following ([CMOS, paragraph 8.159](https://www.chicagomanualofstyle.org/book/ed17/part2/ch08/psec159.html) is the source, but you need to have at least a free trial subscription and log in):

> The conventions of headline style are governed mainly by emphasis and grammar. The following rules, though occasionally arbitrary, are intended primarily to facilitate the consistent styling of titles mentioned or cited in text and notes:
> 
> 1. Capitalize the first and last words in titles and subtitles (but see rule 7), and capitalize all other major words (nouns, pronouns, verbs, adjectives, adverbs, and some conjunctions—but see rule 4).
> 2. Lowercase the articles `the`, `a`, and `an`.
> 3. Lowercase prepositions, regardless of length, except when they are used adverbially or adjectivally (`up` in `Look Up`, `down` in `Turn Down`, `on` in `The On Button`, `to` in `Come To`, etc.) or when they compose part of a Latin expression used adjectivally or adverbially (`De Facto`, `In Vitro`, etc.).
> 4. Lowercase the common coordinating conjunctions `and`, `but`, `for`, `or`, and `nor`.
> 5. Lowercase `to` not only as a preposition (rule 3) but also as part of an infinitive (`to Run`, `to Hide`, etc.), and lowercase `as` in any grammatical function.
> 6. Lowercase the part of a proper name that would be lowercased in text, such as `de` or `von`.
> 7. Lowercase the second part of a species name, such as `fulvescens` in `Acipenser fulvescens`, even if it is the last word in a title or subtitle.

**Comment by tukusejssirs** [comment]
[Deleted as I wanted to place this comment into different issue.]

**Pull request closed without merging**
