### PR TITLE
docs: code of conduct

### LINKED ISSUE #59: Create `CODE_OF_CONDUCT.MD`
I suggest to create `CODE_OF_CONDUCT.MD` and copy there the [Contributor Covenant v1.4](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). I read it and I think is good.

### PR DESCRIPTION
**Pull request by TobiTenno**
closes #59

### CODE REVIEW

**Comment by tukusejssirs** [comment]
Thanks, @TobiTenno, for creating the PR.

I agree with you that the emails from the romcal email address should be forwarded to each of us. If there is no such adress created, could create something like romcal@proton.me? I presume romcal@romcal.org (or some other TLD) would be the best though. :wink:

We could also use a suffix (or whatever it is called), e.g. `romcal+security@...` for specific stuff.

This email address could be used for sources shared with us privately (for now, I asked contributors to send them directly to me, however, it might be better to send them to a romcal email address, e.g. `romcal+sources@...`).

**Comment by tukusejssirs** [comment]
Anyway, why did you set Prettier to ignore MD files? :thinking:

**Comment by TobiTenno** [comment]
> Anyway, why did you set Prettier to ignore MD files? 🤔

@tukusejssirs I was seeing it reformat parts that seemed odd. I'll run it again and see if it doesn't look as messy.

**Comment by TobiTenno** [comment]
> Thanks, @TobiTenno, for creating the PR.
> 
> I agree with you that the emails from the romcal email address should be forwarded to each of us. If there is no such adress created, could create something like [romcal@proton.me](mailto:romcal@proton.me)? I presume [romcal@romcal.org](mailto:romcal@romcal.org) (or some other TLD) would be the best though. 😉
> 
> We could also use a suffix (or whatever it is called), e.g. `romcal+security@...` for specific stuff.
> 
> This email address could be used for sources shared with us privately (for now, I asked contributors to send them directly to me, however, it might be better to send them to a romcal email address, e.g. `romcal+sources@...`).

@tukusejssirs 

I'm happy to go make this, but I'd rather collab w/ you and @emagnier (probably privately for this kind of thing) and sync up

**Comment by TobiTenno** [comment]
looks like i just wasn't looking close enough at the formatting it was prompting, @tukusejssirs, i've backed out the ignore and formatted the COC

**Comment by tukusejssirs** [comment]
> I'm happy to go make this, but I'd rather collab w/ you and @emagnier (probably privately for this kind of thing) and sync up

Okay. When do you to have time for a quick chat regarding this? Where should we chat (gMeet, Discord, …)?

And sorry, I have disabled auto-merging for this PR unintentionally.

**Comment by TobiTenno** [comment]
@tukusejssirs @emagnier email updated

**Review by tukusejssirs — APPROVED** [review]

**Pull request merged**
